// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvJqwX3vlxQcHIR5C4VA_QEFCKw4n3BE',
    appId: '1:498935439048:web:de1e448116ee9b9f128ffd',
    messagingSenderId: '498935439048',
    projectId: 'voft-8bf08',
    authDomain: 'voft-8bf08.firebaseapp.com',
    storageBucket: 'voft-8bf08.appspot.com',
    measurementId: 'G-HMZXNXDP9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALw6kF-J6yF9TSpdXGFt2CSli8j5jRT6o',
    appId: '1:498935439048:android:b583d4932f287130128ffd',
    messagingSenderId: '498935439048',
    projectId: 'voft-8bf08',
    storageBucket: 'voft-8bf08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ImB9_WOtQgJyrqvevn0C6_f_1htZ8JI',
    appId: '1:498935439048:ios:1106f3427da2f8c9128ffd',
    messagingSenderId: '498935439048',
    projectId: 'voft-8bf08',
    storageBucket: 'voft-8bf08.appspot.com',
    iosBundleId: 'com.example.vof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ImB9_WOtQgJyrqvevn0C6_f_1htZ8JI',
    appId: '1:498935439048:ios:849133b014e95914128ffd',
    messagingSenderId: '498935439048',
    projectId: 'voft-8bf08',
    storageBucket: 'voft-8bf08.appspot.com',
    iosBundleId: 'com.example.vof.RunnerTests',
  );
}
